version: '3.9'
services:
  nginx: 
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./docker/nginx/development/Dockerfile
    ports:
      - 80:80
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
      - ./docker/nginx/development:/etc/nginx/conf.d
    depends_on: 
      - api
  api:
    container_name: core_app
    build: .
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    command: >
      sh -c " python manage.py migrate &&
          gunicorn eshop.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media

volumes:
  static_volume:
  media_volume: